### ISSUE TITLE
Cuda out of memory when validation

### ISSUE THREAD

**Issue by CometMoon** [Pongpisit-Thanasutives/Variations-of-SFANet-for-Crowd-Counting#16]
I have tried to test the SFANet model on UCF-QNRF dataset. It is okay in the training epoches, but when it starts the validation set, the error CUDA out of memory appears. I tried to run in both local machine (5GB GiB) and Google Colab (12GB GiB), both of them gave the same error message. Could you give me some suggestions? Thank you.

The exception is raised at models\M_SFANet_UCF_QNRF.py:
"input = torch.cat([input, conv3_3, F.interpolate(conv5_4, scale_factor=2, mode='bilinear', align_corners=True)], 1)"

**Comment by Pongpisit-Thanasutives** [comment]
You can try these...
1. Resizing the validation images, but might affect the final performance.
2. Use the patch-based evaluation method (See SANet for the example, https://openaccess.thecvf.com/content_ECCV_2018/papers/Xinkun_Cao_Scale_Aggregation_Network_ECCV_2018_paper.pdf), so that you can feed the smaller input. This might affect the final performance as well.
3. Deduct the residual connection which causes the problem, but might affect the final performance.
4. Try torch.cuda.empty_cache() or improve the code efficiency.
5. Don't store training and validation set concurrently in the GPU mem.

**Comment by CometMoon** [comment]
Thank you for the suggestions. I resize the image and is now waiting the training to end.
