### ISSUE TITLE
Session crashed after using all available RAM

### ISSUE THREAD

**Issue by AminaZarief** [Pongpisit-Thanasutives/Variations-of-SFANet-for-Crowd-Counting#26]
Hello, 
Thanks for your greatest effort, it really helps me a lot, but I have an issue when testing on the image(img_0071.jpg), the question here, Is the suggested model take more than 13GB RAM?, I have already followed the  instructions suggested in the example code, but it gave me "Session crashed after using all available RAM"

**Comment by Pongpisit-Thanasutives** [comment]
@AminaZarief 
I am sorry for such high use of computational resources. I tested on Google Colab's GPU and got a similar result. 
For now, a simple solution could be dividing the target image into 4 equal patches and then estimating the counts for each of them.

Thank you for the issue, I might also change the example image since it's quite large in resolution.

**Comment by AminaZarief** [comment]
> @AminaZarief I am sorry for such high use of computational resources. I tested on Google Colab's GPU and got a similar result. For now, a simple solution could be dividing the target image into 4 equal patches and then estimating the counts for each of them.
> 
> Thank you for the issue, I might also change the example image since it's quite large in resolution.

Thank you for your reply, I will give it a try
