### ISSUE TITLE
UCF-QNRF weights missing

### ISSUE THREAD

**Issue by reedless** [Pongpisit-Thanasutives/Variations-of-SFANet-for-Crowd-Counting#31]
Hi, I've tried downloading Paper's_weights_UCF_QNRF.zip from both Google Drive and OneDrive, but both zip files are empty and do not contain the .pth files. Could you please upload them again? Thanks!

**Comment by Pongpisit-Thanasutives** [comment]
I have uploaded the pretrained weights to [a new GoogleDrive link](https://drive.google.com/drive/folders/1s96O4-yW0EwZGVeHgxFGvh4f5LSsejfd?usp=sharing). 
Please let me know if there are problems with it.
By the way, the previous GoogleDrive and OneDrive links are still workable for me.

Thank you for your interest in this research.

**Comment by reedless** [comment]
Hi, thank you so much for the quick response! Is it expected for the zip folder to only be 177.8MB? When I unzip it using Windows there's nothing inside except .DS_Store and ._Paper's_weights_UCF_QNRF. Is there another method I should be using to unzip it? Thanks again!

**Comment by Pongpisit-Thanasutives** [comment]
I see the problem was about unzipping. In Windows, [WinRAR](https://www.win-rar.com/) should do the job after downloading the zipped files.
Anyways for convenience, you can directly download each .pth file via [Paper's_weights_UCF_QNRF](https://drive.google.com/drive/folders/1mYS12BpAO8UBDb2aoOQWRMNviQFy_TVv?usp=share_link) or [ShanghaitechWeights](https://drive.google.com/drive/folders/1m8pRf_Y7uk0-ZjBYSGh_DixfH3ZwynIE?usp=share_link) without having to unzip.

If you still cannot access the files, please let me know.
Thanks!

**Comment by reedless** [comment]
I see, thank you very much!
